Vagrant.configure("2") do |config|
  config.vm.define "dev" do |dev|
    dev.vm.box = "archlinux/archlinux"
    # TODO
    # dev.vm.network "private_network", ip: "192.168.33.11"
    dev.vm.hostname = "gurv-dev"
    # dev.ssh.forward_agent = true
    # dev.ssh.port = 2222    
    # dev.vm.synced_folder ".", "/vagrant"
    dev.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
    end
    config.vm.provision :ansible do |ansible|
      ansible.playbook = ENV.fetch('PLAYBOOK_DIR', '.') + "/all_roles.yml"
      ansible.tags = ["gurv", "gurv-dev"]
      ansible.limit = "gurv-dev"
    end
  end
end